apiVersion: v1
kind: Secret
metadata:
  name: uber-secrets
  namespace: uber-clone
type: Opaque
stringData:
  POSTGRES_USER: "uber"
  POSTGRES_PASSWORD: "uberpassword"
  POSTGRES_DB: "uberdb"
  GRAFANA_ADMIN_PASSWORD: "admin"
