global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api_gateway'
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'ride_service'
    static_configs:
      - targets: ['host.docker.internal:8002']

  - job_name: 'driver_service'
    static_configs:
      - targets: ['host.docker.internal:8003']

  - job_name: 'matching_service'
    static_configs:
      - targets: ['host.docker.internal:8004']

  - job_name: 'location_service'
    static_configs:
      - targets: ['host.docker.internal:8005']
